ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'LOT_ACQUIRED';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'COMPLETED_FOR_SALE';
ALTER TYPE "ProjectStatus" ADD VALUE IF NOT EXISTS 'COMPLETED_FOR_RENT';
